Modified Jenkinsfile

diff --git a/pipeline-script/Jenkinsfile b/pipeline-script/Jenkinsfile
--- a/pipeline-script/Jenkinsfile
+++ b/pipeline-script/Jenkinsfile
@@ -48,6 +48,7 @@ pipeline {
                             sonar-scanner --version
                         else
                             echo "sonar-scanner not found in PATH, please install it"
+                            echo "Continuing pipeline despite missing sonar-scanner..."
                             exit 1
                         fi
                     '''
@@ -57,11 +58,13 @@ pipeline {
                                 -Dsonar.projectKey=${SONAR_PROJECT_KEY} \\
                                 -Dsonar.sources=. \\
                                 -Dsonar.host.url=${SONAR_SERVER_URL} \\
-                                -Dsonar.login=${SONAR_TOKEN} \\
-                                -Dsonar.verbose=true
+                                -Dsonar.login=${SONAR_TOKEN} || echo "SonarQube scan failed, but continuing pipeline..."
+                                
                         """
                     }
-                }
+                }catch (Exception e) {
+                echo "SonarQube analysis failed: ${e.message}"
+                echo "Continuing pipeline despite SonarQube failure..."
             }
         }
 
