Modified Jenkinsfile

diff --git a/pipeline-script/Jenkinsfile b/pipeline-script/Jenkinsfile
--- a/pipeline-script/Jenkinsfile
+++ b/pipeline-script/Jenkinsfile
@@ -6,7 +6,7 @@ pipeline {
         ECR_REPOSITORY = 'amazon-clone'
         IMAGE_NAME = 'amazon-clone'
         SONAR_PROJECT_KEY = 'amazon-clone'
-        SONAR_SERVER_URL = 'http://<new-sonarqube-server-ip>:9000' // Update with the new SonarQube server IP
+        SONAR_SERVER_URL = 'http://3.82.55.175:9000'
         KUBERNETES_MANIFEST_REPO = 'https://github.com/Nalla06/k8s-manifests.git'
         KUBERNETES_MANIFEST_PATH = 'deployment.yml'
         EKS_CLUSTER_NAME = 'amazon-cluster'
@@ -40,27 +40,24 @@ pipeline {
                 JAVA_HOME = '/usr/lib/jvm/java-17-openjdk-amd64' // Ensure Java 17 is used
             }
             steps {
-                withCredentials([string(credentialsId: 'sonar-token', variable: 'SONAR_TOKEN')]) {
-                    script {
-                        sh '''
-                            if command -v sonar-scanner > /dev/null; then
-                                echo "sonar-scanner found at $(which sonar-scanner)"
-                                sonar-scanner --version
-                            else
-                                echo "sonar-scanner not found in PATH, please install it"
-                                exit 1
-                            fi
-                        '''
-                        withSonarQubeEnv('SonarQube') {
-                            sh """
-                                sonar-scanner -X \\
-                                    -Dsonar.projectKey=${SONAR_PROJECT_KEY} \\
-                                    -Dsonar.sources=. \\
-                                    -Dsonar.host.url=${SONAR_SERVER_URL} \\
-                                    -Dsonar.login=${SONAR_TOKEN} \\
-                                    -Dsonar.javascript.lcov.reportPaths=coverage/lcov.info
-                            """
-                        }
+                script {
+                    sh '''
+                        if command -v sonar-scanner > /dev/null; then
+                            echo "sonar-scanner found at $(which sonar-scanner)"
+                            sonar-scanner --version
+                        else
+                            echo "sonar-scanner not found in PATH, please install it"
+                            exit 1
+                        fi
+                    '''
+                    withSonarQubeEnv('SonarQube') {
+                        sh """
+                            sonar-scanner -X \\
+                                -Dsonar.projectKey=${SONAR_PROJECT_KEY} \\
+                                -Dsonar.sources=. \\
+                                -Dsonar.host.url=${SONAR_SERVER_URL} \\
+                                -Dsonar.javascript.lcov.reportPaths=coverage/lcov.info
+                        """
                     }
                 }
             }
